@baseUrl = http://localhost:8081
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGFuYW5oQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1NDA3NzgzLCJleHAiOjE3ODU0MTEzODN9.3riyWh6p08eBXYbUqKf2YL4g4OE0JqAu1O4L0z5ugmY

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "fullName": "Admin",
  "email":"phananh@gmail.com",
  "password":"123456"
}

###

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "phananh@gmail.com",
  "password":"123456"
}

###

### Get Me
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{token}}