@baseUrl = http://localhost:8080

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "fullName": "Phan Anh",
  "email":"phananh@gmail.com",
  "password":"123456"
}

###

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "phananh@gmail.com1111",
  "password":"123456"
}