@baseUrl = http://localhost:8080

### Get products (with optional search and pagination)
GET {{baseUrl}}/products?page=0&size=5&keyword=iphone
Accept: application/json

###

### Create a new product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Laptop Dell XPS",
  "price": -1500.0,
  "stock": 10
}

###

### Get a product by ID
GET {{baseUrl}}/products/5
Accept: application/json

###

### Update a product
PUT {{baseUrl}}/products/5
Content-Type: application/json

{
  "name": "Laptop Dell XPS 15",
  "price": 1600.0,
  "stock": 15
}

###

### Delete a product
DELETE {{baseUrl}}/products/10
